# Generated by Django 3.2.25 on 2025-05-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_alter_service_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='owner',
        ),
    ]
