# Generated by Django 3.2.25 on 2025-05-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_remove_service_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service_app.user'),
            preserve_default=False,
        ),
    ]
